#!/usr/bin/env python3
"""
Digest Quality Evaluation Script

Evaluates digest scripts generated by different models using a standardized rubric.
Uses Claude to analyze and grade each digest across multiple quality dimensions.
"""

import os
import sys
import json
from pathlib import Path
from datetime import datetime
from typing import Dict, List, Optional

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent.parent))

# Load environment variables
env_path = Path(__file__).parent.parent / '.env'
if env_path.exists():
    for line in env_path.read_text().splitlines():
        if '=' in line and not line.startswith('#'):
            key, _, value = line.partition('=')
            os.environ[key.strip()] = value.strip()


EVALUATION_RUBRIC = """
# Digest Quality Evaluation Rubric

Evaluate the digest script on the following dimensions, scoring each from 1-10:

## 1. Episode Coverage & Comprehensiveness (Weight: 20%)
- Does the digest discuss ALL episodes provided?
- Are insights from the FULL transcript included (beginning, middle, AND end sections)?
- Does it avoid falsely claiming transcripts are missing or unavailable?
- Does it cover the major stories, themes, and takeaways from each episode?

Score 1-3: Misses episodes, claims missing transcripts, or only covers surface content
Score 4-6: Covers most episodes but misses depth or sections of transcripts
Score 7-9: Good comprehensive coverage of all episodes
Score 10: Exceptional coverage - clearly uses entire transcripts, captures all key points

## 2. Content Quality & Insight Depth (Weight: 20%)
- Are insights meaningful, substantive, and analytical?
- Does it go beyond surface summaries to provide genuine analysis?
- Does it make interesting connections between episodes or to broader trends?
- Does it include specific facts, quotes, or data points from the transcripts?

Score 1-3: Shallow, generic, or mostly paraphrasing titles
Score 4-6: Some insights but lacking depth or specificity
Score 7-9: Good analytical insights with specific details
Score 10: Excellent nuanced analysis with compelling connections and specifics

## 3. Conversational Dialogue Quality (Weight: 15%)
- Does it read as natural, engaging conversation between two people?
- Do the speakers have distinct roles (Host asks, Analyst explains/analyzes)?
- Is there genuine back-and-forth with interruptions, reactions, agreements, disagreements?
- Does it avoid long monologues or robotic turn-taking?
- Does the conversation flow logically from topic to topic?

Score 1-3: Stilted, robotic, or monologue-heavy
Score 4-6: Basic dialogue but mechanical or unnatural
Score 7-9: Natural conversation with good dynamics
Score 10: Excellent - reads like real podcast hosts with chemistry and personality

## 4. ElevenLabs Audio Tag Usage (Weight: 15%)
- Uses audio tags correctly: [tag] placed AFTER "SPEAKER_N:" colon
- Uses VARIETY of audio tags (excited, thoughtful, concerned, hopeful, curious, etc.)
- Tags match the emotional content of the dialogue
- Tags are used appropriately - not too sparse, not overused
- Tags include both emotions AND delivery style cues

Score 1-3: Missing tags, wrong format, or repetitive single tag
Score 4-6: Basic tags but limited variety or mismatched emotions
Score 7-9: Good variety and appropriate emotional matching
Score 10: Excellent - varied, contextually perfect tag usage that enhances delivery

## 5. Personality, Humor & Entertainment Value (Weight: 10%)
- Does the script have personality and voice, not generic AI output?
- Are there moments of humor, wit, or lightness where appropriate?
- Is it engaging and entertaining to read/listen to?
- Do the hosts have character and chemistry?
- Does it avoid being dry, corporate, or overly formal?

Score 1-3: Dry, generic, no personality
Score 4-6: Some personality but mostly bland
Score 7-9: Good personality with entertaining moments
Score 10: Excellent - genuinely fun to read with distinct character voices

## 6. Format Compliance & Technical Correctness (Weight: 10%)
- Follows SPEAKER_1:/SPEAKER_2: format exactly (colon immediately after number)
- Proper structure with clear speaker transitions
- No broken formatting, orphaned tags, or malformed lines
- Consistent throughout the entire script

Score 1-3: Significant format violations
Score 4-6: Minor format issues
Score 7-9: Good format with rare minor issues
Score 10: Perfect format compliance throughout

## 7. Accuracy & Truthfulness (Weight: 10%)
- Does NOT falsely claim to lack access to transcripts
- Does NOT hallucinate facts, names, or details
- Accurately represents what each episode discusses
- Correctly attributes information to the right episode
- No made-up quotes or fabricated content

Score 1-3: Contains hallucinations or false claims about access
Score 4-6: Minor inaccuracies or attribution errors
Score 7-9: Mostly accurate with verifiable content
Score 10: Fully accurate - all claims traceable to source transcripts

---

After evaluating each dimension, provide:
1. Individual dimension scores (1-10) with brief justification
2. Weighted total score (0-100)
3. Key strengths (3-5 bullet points with specific examples from the script)
4. Key weaknesses (3-5 bullet points with specific examples)
5. Memorable moments (any particularly good/bad lines or sections)
6. Overall assessment (3-4 sentences summarizing quality and fit for purpose)
"""


def load_digests(comparison_dir: Path) -> Dict[str, str]:
    """Load digest scripts from the comparison directory."""
    digests = {}

    for md_file in comparison_dir.glob("*.md"):
        model_name = md_file.stem.rsplit('_', 2)[0].replace('_', ' ')
        digests[model_name] = md_file.read_text()

    return digests


def load_summary(comparison_dir: Path) -> Optional[Dict]:
    """Load the test summary file."""
    summary_files = list(comparison_dir.glob("summary_*.json"))
    if summary_files:
        latest = max(summary_files, key=lambda p: p.stat().st_mtime)
        return json.loads(latest.read_text())
    return None


def call_claude_p(prompt: str, timeout: int = 300) -> str:
    """Call Claude via claude -p (programmatic mode) instead of direct API.

    Uses the Claude Code CLI's programmatic mode, which runs on the existing
    Claude subscription instead of per-token API billing.

    Args:
        prompt: The full prompt text to send
        timeout: Subprocess timeout in seconds (default 5 min)

    Returns:
        The text response from Claude
    """
    import subprocess

    claude_path = os.path.expanduser("~/.local/bin/claude")
    if not os.path.exists(claude_path):
        claude_path = "claude"  # Fall back to system PATH

    env = os.environ.copy()
    env.pop("CLAUDECODE", None)  # Allow running from within Claude Code context

    result = subprocess.run(
        [claude_path, "-p", "-"],
        input=prompt,
        capture_output=True,
        text=True,
        timeout=timeout,
        env=env,
    )

    if result.returncode != 0:
        raise RuntimeError(f"claude -p failed (exit {result.returncode}): {result.stderr[:500]}")

    return result.stdout.strip()


def evaluate_digest(
    digest_content: str,
    model_name: str,
    episode_info: List[Dict],
    evaluator_model: str = "claude-sonnet-4-20250514"
) -> Dict:
    """Evaluate a single digest using Claude as the evaluator.

    Uses claude -p (programmatic mode) instead of direct Anthropic API.
    """

    # ┌─────────────────────────────────────────────────────────────────────┐
    # │ PREVIOUS IMPLEMENTATION: Direct Anthropic API call                  │
    # │ To revert: uncomment this block, remove the call_claude_p() call   │
    # │ below, and restore 'import anthropic' at line 153.                 │
    # │                                                                     │
    # │ import anthropic                                                    │
    # │ client = anthropic.Anthropic(api_key=os.getenv('ANTHROPIC_API_KEY'))│
    # │ response = client.messages.create(                                  │
    # │     model=evaluator_model,                                          │
    # │     max_tokens=2000,                                                │
    # │     messages=[{"role": "user", "content": evaluation_prompt}]       │
    # │ )                                                                   │
    # │ result_text = response.content[0].text.strip()                      │
    # └─────────────────────────────────────────────────────────────────────┘

    # Build evaluation prompt
    episodes_desc = "\n".join([
        f"- Episode {i+1}: \"{ep['title']}\" ({ep['transcript_length']:,} chars, AI score: {ep['ai_score']:.2f})"
        for i, ep in enumerate(episode_info)
    ])

    evaluation_prompt = f"""You are evaluating a podcast digest script generated by {model_name}.

## Episodes That Were Provided (with FULL transcripts, no truncation):
{episodes_desc}

Total transcript content provided: {sum(ep['transcript_length'] for ep in episode_info):,} characters

## Evaluation Rubric:
{EVALUATION_RUBRIC}

## Digest Script to Evaluate:

```
{digest_content}
```

---

Please evaluate this digest according to the rubric above. Provide your response in the following JSON format:

{{
    "episode_coverage": {{
        "score": <1-10>,
        "justification": "<brief justification for score>"
    }},
    "content_quality": {{
        "score": <1-10>,
        "justification": "<brief justification>"
    }},
    "dialogue_quality": {{
        "score": <1-10>,
        "justification": "<brief justification>"
    }},
    "audio_tag_usage": {{
        "score": <1-10>,
        "justification": "<brief justification>",
        "tag_variety": ["list", "of", "tags", "used"]
    }},
    "personality_entertainment": {{
        "score": <1-10>,
        "justification": "<brief justification>"
    }},
    "format_compliance": {{
        "score": <1-10>,
        "justification": "<brief justification>"
    }},
    "accuracy_truthfulness": {{
        "score": <1-10>,
        "justification": "<brief justification>",
        "claims_missing_transcripts": <true/false>
    }},
    "weighted_total": <0-100>,
    "strengths": ["<strength with specific example>", ...],
    "weaknesses": ["<weakness with specific example>", ...],
    "memorable_moments": {{
        "good": ["<quote or description of good moment>", ...],
        "bad": ["<quote or description of problematic moment>", ...]
    }},
    "overall_assessment": "<3-4 sentence summary>"
}}

Return ONLY the JSON, no other text.
"""

    try:
        result_text = call_claude_p(evaluation_prompt, timeout=300)

        # Parse JSON from response (handle markdown fences if present)
        if result_text.startswith("```"):
            result_text = result_text.split("```")[1]
            if result_text.startswith("json"):
                result_text = result_text[4:]

        return json.loads(result_text)

    except Exception as e:
        return {
            "error": str(e),
            "weighted_total": 0,
            "overall_assessment": f"Evaluation failed: {e}"
        }


def run_evaluation(comparison_dir: Optional[Path] = None) -> Dict:
    """Run evaluation on all digests in the comparison directory."""
    print("=" * 80)
    print("DIGEST QUALITY EVALUATION")
    print("=" * 80)
    print()

    # Find comparison directory
    if comparison_dir is None:
        base_dir = Path(__file__).parent.parent / 'data' / 'model_comparison'
        # Use most recent if multiple
        comparison_dir = base_dir

    if not comparison_dir.exists():
        print(f"ERROR: Comparison directory not found: {comparison_dir}")
        return {}

    # Load digests
    print("1. Loading digest scripts...")
    digests = load_digests(comparison_dir)
    print(f"   Found {len(digests)} digests: {', '.join(digests.keys())}")
    print()

    # Load summary for episode info
    print("2. Loading test summary...")
    summary = load_summary(comparison_dir)
    if not summary:
        print("   WARNING: No summary file found, using placeholder episode info")
        episode_info = [{"title": "Unknown", "transcript_length": 0, "ai_score": 0}]
    else:
        episode_info = summary.get("episodes", [])
        print(f"   Found {len(episode_info)} episodes in summary")
    print()

    # Evaluate each digest
    print("3. Evaluating digests...")
    print()

    evaluations = {}
    for model_name, digest_content in digests.items():
        print(f"   Evaluating {model_name}...")
        evaluation = evaluate_digest(
            digest_content=digest_content,
            model_name=model_name,
            episode_info=episode_info
        )
        evaluations[model_name] = evaluation

        if "error" not in evaluation:
            print(f"   - Score: {evaluation.get('weighted_total', 'N/A')}/100")
        else:
            print(f"   - ERROR: {evaluation.get('error')}")
        print()

    # Save evaluations
    print("4. Saving evaluation results...")
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    eval_path = comparison_dir / f"evaluation_{timestamp}.json"
    eval_path.write_text(json.dumps(evaluations, indent=2))
    print(f"   Saved: {eval_path.name}")
    print()

    # Print results table
    print("=" * 80)
    print("EVALUATION RESULTS")
    print("=" * 80)
    print()

    # Header
    print(f"{'Model':<18} {'Cover':<7} {'Content':<8} {'Dialog':<7} {'Tags':<6} {'Person':<7} {'Format':<7} {'Accur':<6} {'TOTAL':<7}")
    print("-" * 80)

    # Sort by total score
    sorted_evals = sorted(
        evaluations.items(),
        key=lambda x: x[1].get('weighted_total', 0),
        reverse=True
    )

    for model_name, eval_data in sorted_evals:
        if "error" in eval_data:
            print(f"{model_name:<18} {'ERROR':<62}")
            continue

        coverage = eval_data.get('episode_coverage', {}).get('score', 'N/A')
        content = eval_data.get('content_quality', {}).get('score', 'N/A')
        dialogue = eval_data.get('dialogue_quality', {}).get('score', 'N/A')
        tags = eval_data.get('audio_tag_usage', {}).get('score', 'N/A')
        personality = eval_data.get('personality_entertainment', {}).get('score', 'N/A')
        format_score = eval_data.get('format_compliance', {}).get('score', 'N/A')
        accuracy = eval_data.get('accuracy_truthfulness', {}).get('score', 'N/A')
        total = eval_data.get('weighted_total', 'N/A')

        print(f"{model_name:<18} {coverage:<7} {content:<8} {dialogue:<7} {tags:<6} {personality:<7} {format_score:<7} {accuracy:<6} {total:<7}")

    print("-" * 80)
    print()

    # Print detailed assessments
    print("DETAILED ASSESSMENTS:")
    print("=" * 80)

    for model_name, eval_data in sorted_evals:
        if "error" in eval_data:
            continue

        print(f"\n{'='*80}")
        print(f"### {model_name}")
        print(f"### Total Score: {eval_data.get('weighted_total', 'N/A')}/100")
        print("="*80)

        # Dimension scores with justifications
        print("\nDIMENSION SCORES:")
        print("-" * 40)

        dims = [
            ('episode_coverage', 'Episode Coverage (20%)'),
            ('content_quality', 'Content Quality (20%)'),
            ('dialogue_quality', 'Dialogue Quality (15%)'),
            ('audio_tag_usage', 'Audio Tag Usage (15%)'),
            ('personality_entertainment', 'Personality/Entertainment (10%)'),
            ('format_compliance', 'Format Compliance (10%)'),
            ('accuracy_truthfulness', 'Accuracy/Truthfulness (10%)')
        ]

        for key, label in dims:
            dim_data = eval_data.get(key, {})
            score = dim_data.get('score', 'N/A')
            justification = dim_data.get('justification', '')
            print(f"\n{label}: {score}/10")
            if justification:
                print(f"   {justification}")

        print("\n" + "-" * 40)
        print("\nSTRENGTHS:")
        for strength in eval_data.get('strengths', []):
            print(f"  ✓ {strength}")

        print("\nWEAKNESSES:")
        for weakness in eval_data.get('weaknesses', []):
            print(f"  ✗ {weakness}")

        # Memorable moments with excerpts
        moments = eval_data.get('memorable_moments', {})
        if moments:
            print("\nMEMORABLE EXCERPTS:")
            good_moments = moments.get('good', [])
            bad_moments = moments.get('bad', [])

            if good_moments:
                print("\n  Good moments:")
                for moment in good_moments[:3]:
                    print(f"    \"{moment}\"")

            if bad_moments:
                print("\n  Problematic moments:")
                for moment in bad_moments[:3]:
                    print(f"    \"{moment}\"")

        print("\nOVERALL ASSESSMENT:")
        print(f"  {eval_data.get('overall_assessment', 'N/A')}")
        print()

    return evaluations


if __name__ == "__main__":
    run_evaluation()
